#!/bin/sh

ZPOOL="tank"

/sbin/zfs list tank > /dev/null 2>&1

if [ $? -eq 0 ]; then
	zfsfeat=1
else
	zfsfeat=0
fi

/sbin/gpart recover vtbd0  >> /var/log/cloud-apply.log 2>&1

if [ ${zfsfeat} -eq 0 ]; then
	/sbin/gpart resize -i2 vtbd0  >> /var/log/cloud-apply.log 2>&1
else
#	/sbin/gpart recover vtbd0  >> /var/log/cloud-apply.log 2>&1
#	/sbin/gpart resize -i3 /dev/vtbd0 >> /var/log/cloud-apply.log 2>&1
#	/sbin/zpool set autoexpand=on tank >> /var/log/cloud-apply.log 2>&1
#	/sbin/zpool online -e tank /dev/vtbd0p3 >> /var/log/cloud-apply.log 2>&1
	consumer=$( ls -1 /dev/diskid/ | head -n1 )
	last_part=$( ls -1 /dev/diskid/ | tail -n1 )
	p2=${last_part##*${consumer}}
	index=$( echo ${p2} | tr -d [aA-zZ] | awk '{ printf $1 }' )
	/sbin/gpart recover diskid/${consumer}  >> /var/log/cloud-apply.log 2>&1
#       /sbin/gpart recover vtbd0  >> /var/log/cloud-apply.log 2>&1
	/sbin/gpart resize -i${index} diskid/${consumer}  >> /var/log/cloud-apply.log 2>&1
#       /sbin/gpart resize -i3 /dev/vtbd0 >> /var/log/cloud-apply.log 2>&1
	/sbin/zpool set autoexpand=on tank >> /var/log/cloud-apply.log 2>&1
	/sbin/zpool online -e tank diskid/${consumer}${p2}  >> /var/log/cloud-apply.log 2>&1
#       /sbin/zpool online -e tank /dev/vtbd0p3 >> /var/log/cloud-apply.log 2>&1
fi

# CBSD CLOUD addon
/sbin/mount -t cd9660 /dev/iso9660/cidata /mnt
ret=$?

if [ ${ret} -eq 0 ]; then
	ip1=
	gw1=

	if [ -r /mnt/cbsd-network-config ]; then

		echo "found cbsd-network-config" >> /var/log/cloud-apply.log 2>&1

		. /mnt/cbsd-network-config
		/sbin/umount /mnt || true

		echo "cbsd-network-config: ip1[$ip1] gw1[$gw1]" >> /var/log/cloud-apply.log 2>&1

		if [ -n "${ip1}" ]; then
			/usr/sbin/sysrc -q ifconfig_vtnet1= > /dev/null 2>&1
			/usr/sbin/sysrc -q ifconfig_vtnet1_ipv6="${ip1}" > /dev/null 2>&1
			/sbin/ifconfig vtnet1 inet6 ${ip1} up > /dev/null 2>&1
		fi

		if [ -n "${gw1}" ]; then
			/usr/sbin/sysrc -q ipv6_defaultrouter="${gw1}" > /dev/null 2>&1
			/sbin/route -6 add default ${gw1}  > /dev/null 2>&1
		fi
		/usr/bin/killall -9 dhclient
	fi
fi

/etc/rc.d/hostname stop  >> /var/log/cloud-apply.log 2>&1
/etc/rc.d/hostname start  >> /var/log/cloud-apply.log 2>&1
/etc/rc.d/netif stop  >> /var/log/cloud-apply.log 2>&1
/etc/rc.d/netif start  >> /var/log/cloud-apply.log 2>&1
/etc/rc.d/routing stop  >> /var/log/cloud-apply.log 2>&1
/etc/rc.d/routing start  >> /var/log/cloud-apply.log 2>&1

exit 0
